const REJECTED_STATUS = 'REJECTED';
const ACCEPTED_STATUS = 'ACCEPTED';

const NOMINATION_STATUS = [REJECTED_STATUS, ACCEPTED_STATUS];

module.exports = {
  REJECTED_STATUS,
  ACCEPTED_STATUS,
  NOMINATION_STATUS,
};
